DROP TYPE status CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS role_permisstion;
DROP TABLE IF EXISTS role;

DROP TABLE IF EXISTS permission;

DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS order_detail;

DROP TABLE IF EXISTS product CASCADE;

DROP TABLE IF EXISTS product_category;

DROP TABLE IF EXISTS category;

