// Code generated by sqlc. DO NOT EDIT.
// source: product.sql

package domain

import (
	"context"
)

const getProductById = `-- name: GetProductById :one
SELECT id, name_product, price, created_at FROM product
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductById(ctx context.Context, id int64) (Product, error) {
	row := q.queryRow(ctx, q.getProductByIdStmt, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.NameProduct,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}
