// Code generated by sqlc. DO NOT EDIT.

package domain

import (
	"context"
)

type Querier interface {
	CreateOrderDetail(ctx context.Context, arg CreateOrderDetailParams) (OrderDetail, error)
	CreateOrders(ctx context.Context, customerid int64) (Order, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateRolePermisstion(ctx context.Context, roleid int64) (RolePermisstion, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteOrderById(ctx context.Context, id int64) error
	DeleteOrderDetailById(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	GetOrderDetail(ctx context.Context, id int64) (OrderDetail, error)
	GetOrdersById(ctx context.Context, id int64) (Order, error)
	GetProductById(ctx context.Context, id int64) (Product, error)
	GetRole(ctx context.Context, id int64) (Role, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListOrderDetail(ctx context.Context, arg ListOrderDetailParams) ([]OrderDetail, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListRole(ctx context.Context, arg ListRoleParams) ([]Role, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
