// Code generated by sqlc. DO NOT EDIT.
// source: rolePermisstion.sql

package domain

import (
	"context"
)

const createRolePermisstion = `-- name: CreateRolePermisstion :one
INSERT INTO role_permisstion (
    roleid
) VALUES (
  $1
)
RETURNING roleid, permissionid, created_at
`

func (q *Queries) CreateRolePermisstion(ctx context.Context, roleid int64) (RolePermisstion, error) {
	row := q.queryRow(ctx, q.createRolePermisstionStmt, createRolePermisstion, roleid)
	var i RolePermisstion
	err := row.Scan(&i.Roleid, &i.Permissionid, &i.CreatedAt)
	return i, err
}
